spring:
  application:
    name: spring-derby-webserver
  datasource:
    url: jdbc:derby://localhost:1527/test
    username: derbyuser
    password: derbypassword
    driver-class-name: org.apache.derby.jdbc.ClientDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: APP
#        dialect: org.hibernate.dialect.DerbyDialect
server:
  port: 8090